### PR TITLE
Fixing incorrect array handling and adding some of the excluded classes and functions

### PR DESCRIPTION
**Pull request by lalvarezt**
@tpaviot This adds a few more classes, due to partial const array management

### CODE REVIEW

**Comment by tpaviot** [comment]
You should rebase on master and push -force the branch, so that only commit 81d4bcf is part of this PR

**Comment by tpaviot** [comment]
@lalvarezt There's an issue with IntImp module:
```
=== generating SWIG files for module IntImp ===
         parsing IntImp related headers ...done.
         processing typedefs ...done.
         processing enums ...done
         processing classes ...done
         processing free functions ...{'line_number': 24, 'constant': 1, 'name':
 'DPuv', 'reference': 0, 'type': 'const gp_Vec', 'static': 0, 'extern': False, '
pointer': 0}
Traceback (most recent call last):
  File "generate_wrapper.py", line 1454, in <module>
    process_module(module_to_process)
  File "generate_wrapper.py", line 1403, in process_module
    modules_exclude_member_functions)
  File "generate_wrapper.py", line 1290, in __init__
    self._free_functions_str = process_free_functions(free_functions)
  File "generate_wrapper.py", line 957, in process_free_functions
    str_free_functions += process_function(free_function)
  File "generate_wrapper.py", line 926, in process_function
    param_type_and_name = "%s %s[%s]" % (param_type, param["name"], param["array
_size"])
KeyError: 'array_size'
```

**Comment by lalvarezt** [comment]
@tpaviot sorry about the PR, I'm new to this and make a mistake, after the rebase and the pull, something happened and there are other things that I'm working that got mixed with this, don't know how to fix it, sorry for the mess.

**Comment by tpaviot** [comment]
@lalvarezt no problem. Checkout to your branch and type:
```$ git rebase master
$ git push array_management origin -f
```

**Comment by lalvarezt** [comment]
@tpaviot It gives me some error
fatal: 'array_management' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by tpaviot** [comment]
@lalvarezt my fault, I updated the comment please update

**Comment by lalvarezt** [comment]
@tpaviot I did it but nothing happened, it says Everything up-to-date

**Comment by lalvarezt** [comment]
@tpaviot I fixed the error in the IntImp module

**Comment by tpaviot** [comment]
@lalvarezt how ?

**Comment by lalvarezt** [comment]
@tpaviot instead of 
if param['array']:
should be
if 'array_size' in param:

**Comment by lalvarezt** [comment]
@tpaviot I think the repo is fixed now, sorry for all the troubles

**Comment by tpaviot** [comment]
@lalvarezt No problem. Thank you again, reviewing the same day 2 PRs related to the pythonocc-generator, i's almost twice as the total amount received for the 5 past years !

**Comment by lalvarezt** [comment]
@tpaviot No problem, I have some new changes, I should make a new PR soon.

**Comment by tpaviot** [comment]
@lalvarezt Compilation fails on both travis https://travis-ci.org/tpaviot/pythonocc-core/builds/172702507 and appveyor https://ci.appveyor.com/project/tpaviot/pythonocc-core/build/pythonocc-core-0.17.528
This is certainly why I removed the related classes

**Comment by lalvarezt** [comment]
@tpaviot I noticed, the 'NCollection_CellFilter.hxx' cannot be removed yet this is something that I'm working on a different branch, I fixed the PR, it should compile now.

**Comment by lalvarezt** [comment]
@tpaviot Hi, what's the status on this PR, do you still have compile issues after the latest update.

**Comment by tpaviot** [comment]
@lalvarezt I generated the SWIG files and pushed to pythonocc-core. It's currently building.

**Comment by tpaviot** [comment]
@lalvarezt Nope, appveyor build still fails https://ci.appveyor.com/project/tpaviot/pythonocc-core/build/pythonocc-core-0.17.530/job/guftecfng6ad55v6

**Comment by lalvarezt** [comment]
@tpaviot That's weird, I have all the PR applied and the whole library compiles on my machine. Let me do some checks

**Comment by jf---** [comment]
it would be quite useful to be able to trigger a CI build when commiting to this directory, right?
would such a port be straightfwd?
in a sense you would like to run the pythonocc-core CI routine, but with the latest commit of this repo

**Comment by tpaviot** [comment]
@lalvarezt What's your OS ? compiler ? Windows MSVC is very different from gcc/Mingw/MSys. In the Modules.py file, I often had to exclude some classes that do not compile on windows.

Another thing, it seems that CI builds are broken since this morning. I can't understand why.

**Comment by jf---** [comment]
@tpaviot , but this repo does not trigger CI builds?

**Comment by lalvarezt** [comment]
@tpaviot I'm using Windows 10 x64, MSVC 2015, Python 3.5. In travis https://travis-ci.org/tpaviot/pythonocc-core/builds/173164418 it says it compiles for python 3.x and fails in 2.x, is that correct.

**Comment by tpaviot** [comment]
@lalvarezt I fixed travis build, pythonocc-core compiles ....

**Comment by tpaviot** [comment]
@lalvarezt I had to remove a few classes. Let me close this PR and open another one that I will merge, with one more commit of mine

**Pull request closed without merging**
