### PR TITLE
Missing handle generation

### PR DESCRIPTION
**Pull request by lalvarezt**
Generating handle declaration for classes that do not have an extra .hxx with the name handle.

### CODE REVIEW

**Comment by tpaviot** [comment]
@lalvarezt which classes are targeted by this change ?

**Comment by lalvarezt** [comment]
@tpaviot The affected classes are

AIS_AngleDimension
AIS_ColoredDrawer
AIS_ColoredShape
AIS_DiameterDimension
AIS_Dimension
AIS_LengthDimension
AIS_PointCloud
AIS_RadiusDimension
AIS_TexturedShape
BRepMesh_DataStructureOfDelaun
BRepMesh_DiscretRoot
BRepMesh_EdgeTessellationExtractor
BRepMesh_EdgeTessellator
BRepMesh_FastDiscret
BRepMesh_FastDiscretFace
BRepMesh_IEdgeTool
BRepMesh_IncrementalMesh
Font_BRepFont
Graphic3d_BoundBuffer
Graphic3d_Buffer
Graphic3d_CStructure
Graphic3d_Camera
Graphic3d_ClipPlane
Graphic3d_IndexBuffer
Graphic3d_MarkerImage
Graphic3d_ShaderObject
Graphic3d_ShaderProgram
Graphic3d_ShaderVariable
Image_AlienPixMap
Image_Diff
Image_PixMap
Image_PixMapData
MeshVS_DummySensitiveEntity
MeshVS_SensitiveFace
MeshVS_SensitiveMesh
MeshVS_SensitivePolyhedron
MeshVS_SensitiveSegment
NCollection_AccAllocator
NCollection_AlignedAllocator
NCollection_BaseAllocator
NCollection_Buffer
NCollection_HeapAllocator
NCollection_IncAllocator
NCollection_WinHeapAllocator
Poly_CoherentTriangulation
Prs3d_PresentationShadow
Select3D_InteriorSensitivePointSet
Select3D_SensitiveBox
Select3D_SensitiveCircle
Select3D_SensitiveCurve
Select3D_SensitiveEntity
Select3D_SensitiveFace
Select3D_SensitiveGroup
Select3D_SensitivePoint
Select3D_SensitivePoly
Select3D_SensitiveSegment
Select3D_SensitiveSet
Select3D_SensitiveTriangle
Select3D_SensitiveTriangulation
Select3D_SensitiveWire
SelectMgr_FrustumBuilder
SelectMgr_Selection
SelectMgr_SensitiveEntity
SelectMgr_ViewerSelector
StdSelect_ViewerSelector3d
V3d_Plane

**Comment by jf---** [comment]
very curious to try `Graphic3d_ShaderProgram`, being able to add shaders will open up a wide spectrum of possibilities...

**Comment by tpaviot** [comment]
@lalvarezt See commit https://github.com/tpaviot/pythonocc-core/commit/ca1ab1b4e8eef8f59586e21fa9dae8f8adbbedbb on pythonocc-core.

**Comment by tpaviot** [comment]
@lalvarezt Everything looks good, thank you. I wait for travis and appveyor builds to be completed before merging.

**Pull request merged**
