### PR TITLE
captures stdout and stderr to a log file

### LINKED ISSUE #10: optionally capture stdout & stderr during wrapper generation / module compilation
erros are than caught in context of the pythonocc module they're related to.
otherwise, you need to capture stderr by copy/pasting from the terminal, which isnt particularly ergonomics.

possible even more important is capturing stderr from building pythonocc, after new SWIG wrappers have been generated. possible something amongs these lines:

* generate make files
* check the build targets, anything that starts with an underscore say `_BRepFill` is a pythonocc target
* grab those targets
* write the target name to stdout, such that its easy to see which build errors relate to what pythonocc module
* call make on that target
* this is also pretty useful once #8 is up and running. if a build breaks, you get decent feedback on what happened, when a CI build fails

[here's a pythonic way to do so redirect stdout & stderr in a context manager / with statement](http://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python/22434262#22434262)

### PR DESCRIPTION
**Pull request by jf---**
this is pretty convenient to captures errors, without having to stare at the terminal to keep track of the wrapper generation process

fixes #10

### CODE REVIEW

**Comment by tpaviot** [comment]
In order to trace builds, I use to:
<pre>
python generate_wrapper.py 1>stdout.txt 2>stderr.txt
</pre>
What are the advantages of this PR over this simple line ?

**Comment by jf---** [comment]
consistent log names, time stamped log files and not burdening the cognitive load of being so unix savvy ;)

merging stdout and stderr is actually pretty important, it makes the log a lot easier to process / grasp

**Comment by tpaviot** [comment]
@jf--- Original stackoverflow source sinppet should be credited. I guess the utils.py come comes from http://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python, right ?

**Comment by jf---** [comment]
Good, point, PR updated...

**Comment by tpaviot** [comment]
This PR makes the code base much more complex for a feature I personally never needed although I spent hundred of hours working on/with the generator. Similar result can be achieved using a single bash line, regarding the 80 lines of python code added.

**Comment by jf---** [comment]
Agreed, this was clearly not the brightest idea...
Just redirection nails it

```bash
python generate_wrapper.py 1>stdout.txt 2>stderr.txt
```

**Pull request closed without merging**
